[package]
name = "multi_tab_text_editor"
description = "A simple multi-tab text editor"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/tanchevk/multi_tab_text_editor"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
iced = { version = "0.13.1", features = ["tokio", "highlighter", "svg", "image", "advanced"] }
iced_aw = { version = "0.11.0", default-features = false, features = ["card", "menu", "quad"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive", "std"] }
serde_json = "1.0"
rfd = "0.15.0"
opener = "0.7.2"
dirs = "5.0.1"
include_dir = { version = "0.7.4", features = ["glob"] }